### PR TITLE
Fix for empty Ref Exception

### PR DESCRIPTION
**Pull request by dahlsailrunner**
This is a proposed fix for the empty reference exception.  Let me know if there are other changes necessary or if something further upstream should be changed rather than this.  Hopefully this helps.

### CODE REVIEW

**Comment by digitalcoyote** [comment]
Thank you, I'll take a look at this as soon as I get a chance, but off-hand nothing looks amiss with your PR.

**Comment by dahlsailrunner** [comment]
Ok cool.  Another couple of questions, though, and I can add some documentation into the readme  if you give me some answers:
* **Which NuGetDefense.json gets used when a build is triggered inside a VS project with NuGetDefense?**  Seems like one gets created alongide solution file and then another inside project directory next to the csproj file.  (I'm trying to add settings to make sure NVD is self-updated, and haven't seen any effect - also trying to Ignore Bootstrap as an experiment to no effect either)
* **How do you ignore a package generically?**  I added Bootstrap with a null version and null package url and that didn't seem to have any effect - wondering if I'm doing something wrong.
* **There may be a bug in the package version evaluation for Bootstrap.** I had version 3.4.1 installed which triggered some vulnerability issues (correct) but then when I updated the version to 4.4.1 the same vulnerabilities persisted during new builds (seems incorrect).  If you agree I can try some experiments to troubleshoot.
* **Is is true that only ONE of the OSSIndex or NVD options should be enabled?**  NVD wins if both are - since the `vulnDict` dictionary is overwritten by the NVD branch in `Program.cs`.  Is that correct / intentional?

**Comment by digitalcoyote** [comment]
- **Which NuGetDefense.json gets used when a build is triggered inside a VS project with NuGetDefense?** It should only be creating a NuGetDefense.json per project file (in the same directory with that project). It uses `$(MSBuildProjectFullPath)` for msbuild to tell it what directory to look at for the config (using `Path.Combine(directory, "NuGetDefense.json")` ) 
- **How do you ignore a package generically?** I'll need to doublecheck, but it should allow that by just listing the name and leaving the rest null (packageurl is readonly anyway).
- **There may be a bug in the package version evaluation for Bootstrap.** I was not able to reproduce this. the version resolutiojn is handled by NuGet/OSSIndex.
 - **Is is true that only ONE of the OSSIndex or NVD options should be enabled?** It passes in the vulnDict when NVD overrides it. The logic within NVD will add to it if the cve is not found in vulnDict.

I'll do some tests to verify that everything is behaving as it should.

**Comment by dahlsailrunner** [comment]
Awesome info.  Let's get my issue resolved, I'll do some tests and assuming everything works out ok, I'll submit a new PR for some readme updates.  Thanks a lot for the help / response.

**Comment by digitalcoyote** [comment]
I added a unit test for this specific case and merged.

**Pull request merged**
